# Generated by Django 4.0.2 on 2022-02-07 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 15, 15, 11, 748268)),
            preserve_default=False,
        ),
    ]
